#!/usr/bin/env python3
"""Write C code for the game: compile a mod's code/ folder into a blob the builder places.

  python urbz_patch.py new <mod>        add code/main.c + code/hooks.txt to a mod (from a template)
  python urbz_patch.py build <mod>      compile code/*.c and *.s -> code/build/patch.bin + patch.json
  python urbz_patch.py build --dir PATH  same, for a mod folder anywhere (tests/mods/...)
  python urbz_patch.py syms             list named game addresses (code/game.sym)

Needs LLVM (clang + ld.lld) only to *compile*. Built mods carry their compiled
blob, so building the ROM never needs a compiler. On Windows: winget install LLVM.

How it works: the code is linked twice, at address 0 and at 0x10000000. Words
that differ by exactly 0x10000000 are pointers into the blob; the builder adds
the blob's real address to them. Call game functions through code/include/game.h
(absolute addresses), never by declaring them extern.
"""
import glob, hashlib, json, os, shutil, struct, subprocess, sys, tempfile

KIT = os.path.dirname(os.path.abspath(__file__))
CODE = os.path.join(KIT, 'code')
PROBE = 0x10000000
CFLAGS = ['--target=armv5te-none-eabi', '-marm', '-mfloat-abi=soft', '-Os', '-ffreestanding',
          '-fno-builtin', '-nostdlib', '-ffunction-sections', '-fdata-sections', '-fno-common',
          '-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables',
          '-Wall', '-Werror=implicit-function-declaration']
LDSCRIPT = """
SECTIONS {
  . = %s;
  .text : { KEEP(*(.text.hook*)) *(.text .text.*) }
  .rodata : { *(.rodata .rodata.*) }
  .data : { *(.data .data.*) }
  . = ALIGN(4);
  __bss_start = .;
  .bss (NOLOAD) : { *(.bss .bss.* COMMON) }
  . = ALIGN(4);
  __bss_end = .;
  /DISCARD/ : { *(.ARM.exidx*) *(.ARM.attributes) *(.comment) }
}
"""

TEMPLATE_C = """#include "game.h"

/* Called once per game tick (30 times a second) while the city runs.
   Hooked in hooks.txt with:  wrap world_tick on_tick */
unsigned ticks;

void on_tick(void)
{
    ticks++;
}
"""
TEMPLATE_HOOKS = """# Hooks for this mod (see urbz_code.py for the full list):
#   call ADDR func   - make the call (BL) at ADDR go to func
#   jump ADDR func   - replace the whole function at ADDR with func
#   wrap ADDR func   - run func first, then carry on (ARM code only)
#   data ADDR hex    - write bytes;   u8|u16|u32 ADDR value - write a number
# ADDR can be a name from code/game.sym.
wrap world_tick on_tick
"""


def find_tool(name):
    """clang / ld.lld / llvm-objcopy / llvm-nm / llvm-readelf from PATH or common install places."""
    exe = name + ('.exe' if os.name == 'nt' else '')
    cands = [shutil.which(name)]
    if os.name == 'nt':
        cands += [os.path.join(os.environ.get(v, ''), 'LLVM', 'bin', exe)
                  for v in ('ProgramFiles', 'ProgramFiles(x86)')]
    cands += sorted(glob.glob('/usr/lib/llvm-*/bin/' + name), reverse=True)
    cands += sorted(glob.glob('/opt/homebrew/opt/llvm/bin/' + name))
    for c in cands:
        if c and os.path.exists(c):
            return c
    sys.exit('error: %s not found. Install LLVM (Windows: winget install LLVM) to compile '
             'code mods. Building ROMs from already-compiled mods does not need it.' % name)


def sym_header():
    from urbz_code import game_symbols
    lines = ['/* Generated by urbz_patch.py from code/game.sym. Do not edit. */',
             '#pragma once']
    for k, v in sorted(game_symbols(KIT).items(), key=lambda kv: kv[1]):
        lines.append('#define ADDR_%s 0x%08XU' % (k, v))
    return '\n'.join(lines) + '\n'


def run(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode:
        sys.exit('error: %s failed:\n%s%s' % (os.path.basename(cmd[0]), p.stdout, p.stderr))
    return p.stdout


def hook_functions(cdir):
    from urbz_code import parse_hooks, game_symbols
    hp = os.path.join(cdir, 'hooks.txt')
    if not os.path.exists(hp):
        return []
    return [arg for kind, _, arg, _ in parse_hooks(hp, game_symbols(KIT))
            if kind in ('call', 'jump', 'wrap')]


def build(mod):
    """mod: a mod name under mods/, or a path to a mod folder."""
    mdir = mod if os.path.isdir(mod) and os.path.sep in mod else os.path.join(KIT, 'mods', mod)
    cdir = os.path.join(mdir, 'code')
    mod = os.path.basename(os.path.normpath(mdir))
    srcs = sorted(f for f in os.listdir(cdir) if f.endswith(('.c', '.s', '.S'))) \
        if os.path.isdir(cdir) else []
    if not srcs:
        sys.exit('error: no .c or .s files in %s' % cdir)
    clang, lld = find_tool('clang'), find_tool('ld.lld')
    objcopy, nm = find_tool('llvm-objcopy'), find_tool('llvm-nm')
    readelf = find_tool('llvm-readelf')
    roots = hook_functions(cdir)
    with tempfile.TemporaryDirectory() as tmp:
        inc = os.path.join(tmp, 'include')
        os.makedirs(inc)
        open(os.path.join(inc, 'game_syms.h'), 'w').write(sym_header())
        objs = []
        for f in srcs + ['runtime.c']:
            src = os.path.join(CODE, 'include', f) if f == 'runtime.c' else os.path.join(cdir, f)
            o = os.path.join(tmp, f + '.o')
            run([clang] + CFLAGS + ['-I', inc, '-I', os.path.join(CODE, 'include'), '-I', cdir,
                                    '-c', src, '-o', o])
            objs.append(o)
        bins, syms = [], None
        for base in (0, PROBE):
            ld = os.path.join(tmp, 'l%x.ld' % base)
            open(ld, 'w').write(LDSCRIPT % hex(base))
            elf = os.path.join(tmp, 'p%x.elf' % base)
            run([lld, '-T', ld, '--gc-sections', '-o', elf] +
                [a for r in roots for a in ('-u', r)] + objs)
            b = os.path.join(tmp, 'p%x.bin' % base)
            run([objcopy, '-O', 'binary', '--only-section=.text', '--only-section=.rodata',
                 '--only-section=.data', elf, b])
            bins.append(open(b, 'rb').read())
            if base == 0:
                syms = {}
                for line in run([nm, '--defined-only', elf]).splitlines():
                    p = line.split()
                    if len(p) == 3:
                        syms[p[2]] = (int(p[0], 16), p[1])
                # nm drops the Thumb bit; the symbol table keeps it (odd value = Thumb
                # function), and the builder needs it to pick BLX over BL.
                for line in run([readelf, '-sW', elf]).splitlines():
                    p = line.split()
                    if len(p) >= 8 and p[3] == 'FUNC' and p[7] in syms and int(p[1], 16) & 1:
                        syms[p[7]] = (syms[p[7]][0] | 1, syms[p[7]][1])
    b0, b1 = bins
    if len(b0) != len(b1):
        sys.exit('error: the blob changes size with its address (unsupported code construct)')
    b0 += bytes(-len(b0) % 4)
    b1 += bytes(-len(b1) % 4)
    relocs, bad = [], []
    for off in range(0, len(b0), 4):
        x, y = struct.unpack_from('<I', b0, off)[0], struct.unpack_from('<I', b1, off)[0]
        if x == y:
            continue
        if (y - x) & 0xFFFFFFFF == PROBE:
            relocs.append(off)
        else:
            bad.append(off)
    if bad:
        sys.exit('error: code at blob offset(s) %s refers to a fixed address in a way that '
                 'cannot be moved (usually a direct call to a game function). Call game '
                 'functions through game.h instead.' % ', '.join('0x%x' % o for o in bad[:8]))
    bss = syms['__bss_end'][0] - syms['__bss_start'][0]
    funcs = {k: v for k, (v, t) in syms.items() if t in 'TtDdBbRr' and not k.startswith('__')
             and not k.startswith('$')}
    missing = [r for r in roots if r not in funcs]
    if missing:
        sys.exit('error: hooks.txt names %s, not defined in the code' % ', '.join(missing))
    out = os.path.join(cdir, 'build')
    os.makedirs(out, exist_ok=True)
    open(os.path.join(out, 'patch.bin'), 'wb').write(b0)
    info = {'relocs': relocs, 'symbols': funcs, 'bss': bss,
            'sources': {f: hashlib.sha1(open(os.path.join(cdir, f), 'rb').read()).hexdigest()
                        for f in srcs + (['hooks.txt'] if os.path.exists(
                            os.path.join(cdir, 'hooks.txt')) else [])}}
    json.dump(info, open(os.path.join(out, 'patch.json'), 'w'), indent=1)
    print('built mods/%s/code/build/patch.bin: %d bytes code+data, %d bytes zeroed, %d pointer(s) '
          'to relocate, %d hook function(s)' % (mod, len(b0), bss, len(relocs), len(roots)))


def new(mod):
    md = os.path.join(KIT, 'mods', mod)
    if not os.path.isdir(md):
        sys.exit('error: no mod named "%s" (create it: python urbz_mod.py new %s)' % (mod, mod))
    cdir = os.path.join(md, 'code')
    os.makedirs(cdir, exist_ok=True)
    for name, text in (('main.c', TEMPLATE_C), ('hooks.txt', TEMPLATE_HOOKS)):
        p = os.path.join(cdir, name)
        if os.path.exists(p):
            print('kept existing ' + p)
        else:
            open(p, 'w', newline='\n').write(text)
            print('wrote ' + p)
    print('next: edit them, then python urbz_patch.py build %s' % mod)


def main(argv):
    if not argv or argv[0] in ('-h', '--help', 'help'):
        print(__doc__)
        return
    sys.path.insert(0, KIT)
    cmd, args = argv[0], argv[1:]
    if cmd == 'build' and args:
        build(args[1] if args[0] == '--dir' and len(args) > 1 else args[0])
    elif cmd == 'new' and args:
        new(args[0])
    elif cmd == 'syms':
        from urbz_code import game_symbols
        for k, v in sorted(game_symbols(KIT).items(), key=lambda kv: kv[1]):
            print('%08x  %s' % (v, k))
    else:
        sys.exit('usage: urbz_patch.py new|build <mod>  |  syms')


if __name__ == '__main__':
    main(sys.argv[1:])
