#!/usr/bin/env python3
"""Compile places.json into sim/sim_data.h (run after editing it).
The data is written by us (what places offer); nothing here comes from the game."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
KINDS = {'food': 1, 'fun': 2, 'social': 4, 'park': 8, 'gym': 16}


def main():
    places = json.load(open(os.path.join(HERE, 'places.json')))['places']
    out = ['/* Generated by make_data.py from places.json. Do not edit. */', '#pragma once',
           '#include <stdint.h>', '',
           'enum { K_FOOD = 1, K_FUN = 2, K_SOCIAL = 4, K_PARK = 8, K_GYM = 16 };',
           'typedef struct { uint8_t area, kinds, cost; } sim_place_t;',
           '', 'static const sim_place_t sim_places[] = {']
    for a in sorted(places, key=int):
        p = places[a]
        k = 0
        for kind in p['kinds']:
            k |= KINDS[kind]
        out.append('    { %d, %d, %d },   /* %s */' % (int(a), k, int(p['cost']), p['name'].replace('*/', '')))
    out += ['};', '#define SIM_N_PLACES %d' % len(places), '']
    open(os.path.join(HERE, 'sim', 'sim_data.h'), 'w', newline='\n').write('\n'.join(out))
    print('wrote sim/sim_data.h: %d places' % len(places))


if __name__ == '__main__':
    main()
