#!/usr/bin/env python3
"""Compile places.json + npcs.json into sim/sim_data.h (run after editing either file).
The data is written by us (what places offer, pay, rent); nothing here comes from the game."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
KINDS = {'food': 1, 'fun': 2, 'social': 4, 'park': 8, 'gym': 16}


def main():
    places = json.load(open(os.path.join(HERE, 'places.json')))['places']
    npcs = json.load(open(os.path.join(HERE, 'npcs.json')))
    d = npcs['default']
    out = ['/* Generated by make_data.py from places.json and npcs.json. Do not edit. */', '#pragma once',
           '#include <stdint.h>', '',
           'enum { K_FOOD = 1, K_FUN = 2, K_SOCIAL = 4, K_PARK = 8, K_GYM = 16 };',
           'typedef struct { uint8_t area, kinds, cost; } sim_place_t;',
           'typedef struct { uint8_t pay; uint8_t rent_div5; uint16_t start_money; uint8_t decay[8]; } sim_tweak_t;',
           '', 'static const sim_place_t sim_places[] = {']
    for a in sorted(places, key=int):
        p = places[a]
        k = 0
        for kind in p['kinds']:
            k |= KINDS[kind]
        out.append('    { %d, %d, %d },   /* %s */' % (int(a), k, int(p['cost']), p['name'].replace('*/', '')))
    out += ['};', '#define SIM_N_PLACES %d' % len(places), '',
            'static const sim_tweak_t sim_tweaks[36] = {']
    for c in range(36):
        t = dict(d)
        t.update(npcs['people'].get(str(31 + c), {}))
        if not 0 <= t['pay'] <= 255 or t['rent'] % 5 or not 0 <= t['rent'] // 5 <= 255:
            raise SystemExit('bad pay/rent for %d' % (31 + c))
        out.append('    { %d, %d, %d, { %s } },%s' % (
            t['pay'], t['rent'] // 5, t['start_money'], ', '.join(str(min(255, x)) for x in t['decay']),
            '   /* %s */' % t['name'] if 'name' in t else ''))
    out += ['};', '']
    open(os.path.join(HERE, 'sim', 'sim_data.h'), 'w', newline='\n').write('\n'.join(out))
    print('wrote sim/sim_data.h: %d places, 36 people' % len(places))


if __name__ == '__main__':
    main()
