#!/usr/bin/env python3
"""Build and run the NPC Life simulation test on the PC (needs a C compiler: clang or gcc).

The people's original timetables come from your own extracted game (project/base.nds) and
are written to orig_tables.h here at test time; that file is never committed."""
import os, shutil, struct, subprocess, sys, tempfile
HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
sys.path.insert(0, KIT)
SCHEDULE_TABLE = 0x020E4FD8


def tables():
    import ndspy.rom
    from urbz_text import project_strings
    arm9 = ndspy.rom.NintendoDSRom.fromFile(os.path.join(KIT, 'project', 'base.nds')).arm9
    u32 = lambda a: struct.unpack_from('<I', arm9, a - 0x02000000)[0]
    try:
        names = project_strings(os.path.join(KIT, "project"))
        names = [names[512 + c].decode("latin-1") if isinstance(names[512 + c], bytes) else names[512 + c] for c in range(36)]
    except Exception:
        names = ['person %d' % (31 + c) for c in range(36)]
    out = []
    for c in range(36):
        p = u32(SCHEDULE_TABLE + 4 * c)
        out.append(bytes(arm9[p - 0x02000000:p - 0x02000000 + 168]) if p else None)
    return out, names


def main():
    t, names = tables()
    h = ['/* Generated by run_test.py from project/base.nds at test time. Never commit. */',
         'static const unsigned char orig_tables[36][168] = {']
    for x in t:
        h.append('  {%s},' % ','.join(str(b) for b in (x or bytes(168))))
    h += ['};', 'static const int has_table[36] = {%s};' % ','.join('1' if x else '0' for x in t),
          'static const char *names[36] = {%s};' % ','.join('"%d %s"' % (31 + c, n.replace('"', ''))
                                                          for c, n in enumerate(names))]
    open(os.path.join(HERE, 'orig_tables.h'), 'w').write('\n'.join(h) + '\n')
    cc = shutil.which('clang') or shutil.which('gcc') or shutil.which('cc')
    if not cc:
        sys.exit('no C compiler found (install clang or gcc)')
    exe = os.path.join(tempfile.mkdtemp(), 'test_sim')
    subprocess.check_call([cc, '-O2', '-Wall', '-o', exe, os.path.join(HERE, 'test_sim.c'),
                           os.path.join(HERE, 'npc_sim.c'), '-I', HERE])
    sys.exit(subprocess.call([exe]))


if __name__ == '__main__':
    main()
