/* Generated by make_data.py from places.json. Do not edit. */
#pragma once
#include <stdint.h>

enum { K_FOOD = 1, K_FUN = 2, K_SOCIAL = 4, K_PARK = 8, K_GYM = 16 };
typedef struct { uint8_t area, kinds, cost; } sim_place_t;

static const sim_place_t sim_places[] = {
    { 0, 18, 0 },   /* Streetball Court */
    { 1, 8, 0 },   /* Bayou */
    { 2, 6, 6 },   /* Carnival */
    { 4, 4, 0 },   /* Glasstown */
    { 9, 10, 0 },   /* Paradise Island */
    { 11, 8, 0 },   /* The River */
    { 12, 5, 10 },   /* Salty's Riverboat */
    { 13, 5, 6 },   /* Sim Quarter Farmer's Market */
    { 19, 12, 0 },   /* Urbania Park */
    { 20, 6, 10 },   /* Glasstown Mega-Mall */
    { 21, 6, 10 },   /* Glasstown Mega-Mall 2 */
    { 27, 5, 9 },   /* Salty's Lounge */
    { 28, 2, 8 },   /* Cinema d'Urbania */
    { 29, 2, 8 },   /* Cinema Theater */
    { 33, 6, 8 },   /* Zeke's Zydeco Club */
    { 34, 5, 6 },   /* Coffee Shop */
    { 35, 1, 8 },   /* Crawfish Shack */
    { 37, 6, 10 },   /* Island Entertainment Center */
    { 39, 2, 10 },   /* Fortune Teller's Shop */
    { 42, 5, 8 },   /* Cafe Z-Bach */
    { 47, 2, 5 },   /* Museum: Floor 1 */
    { 48, 2, 5 },   /* Museum: Floor 2 */
    { 49, 2, 5 },   /* Epoch Museum */
    { 51, 1, 7 },   /* Slice O' Life Pizza */
    { 53, 6, 0 },   /* Artsie Clubhouse */
    { 54, 4, 0 },   /* Rep Group Clubhouse */
    { 55, 6, 0 },   /* Nerdie Clubhouse */
    { 56, 6, 0 },   /* Richie Clubhouse */
    { 57, 6, 0 },   /* Streetie Clubhouse */
    { 62, 1, 5 },   /* Smoothie Shoppe */
    { 64, 16, 0 },   /* Waters' Gym */
    { 72, 5, 12 },   /* Sensei Maki's Sushi Bar */
    { 73, 2, 5 },   /* Second Looks Thrift Emporium */
    { 79, 6, 10 },   /* Club Xizzle */
};
#define SIM_N_PLACES 34
